name: PR Greeter
on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  welcome-message:
    name: Leave Welcome Comment
    runs-on: ubuntu-latest

    steps:
      - name: Create Comment
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            👋 Hi! Thanks for your Pull Request.
            
            🤖 I'm an automated helper. I've run a Checkstyle and a Maven build.
            
            **While you're waiting for the team lead's review, check yourself:**
            - [ ] The code matches our codestyle.xml
            - [ ] The logic doesn't violate the MVC architecture
            - [ ] New methods have Javadoc comments
            
            🚀 *Good luck!*